#Creating Array

1.

In [13]:
import numpy as np
array_1d=np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


2.,

In [14]:
import numpy as np
array_2d=np.arange(1,10).reshape(3,3)
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3.

In [4]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4.

In [5]:
import numpy as np
array=np.random.randint(0,2,10)
print(array)

[0 0 0 0 1 1 1 0 1 1]


In [17]:
random_array=np.random.rand(10)
print(random_array)

[0.88715191 0.34460344 0.13207455 0.49510663 0.5308532  0.0284387
 0.43067475 0.56583564 0.61691284 0.08461864]


5.

In [6]:
import numpy as np
a=np.zeros(10)
print(a)
b=np.ones(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#Array Indexing

6

In [7]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a[2])

30


7.

In [8]:
import numpy as np
a=np.array(range(1,17)).reshape(4,4)
print(a)
print(a[1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
7


8.

In [9]:
import numpy as np
a=np.array([5,10,15,20,25])
print(a[4])


25


9.

In [10]:
import numpy as np
a=np.array([1,3,5,7,9,11])
print([a[1],a[3],a[4]])

[3, 7, 9]


10.

In [11]:
import numpy as np
array=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array)
print(array[1,1,1])


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8


#Array slicing

11.

In [12]:
import numpy as np
a=np.array([2,4,6,8,10,12])
print(a[0:3])

[2 4 6]


12.

In [19]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])
sliced_array = array[:2, -2:]

print("Original Array:")
print(array)

print("\nSliced Array:")
print(sliced_array)



Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Sliced Array:
[[3 4]
 [7 8]]


13.

In [18]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[0::2])

[0 2 4 6 8]


14.

In [21]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
sliced_array = array[:, -2:]
print(sliced_array)

[[ 3  4]
 [ 7  8]
 [11 12]]


15.

In [22]:
import numpy as np
martrix_5x5 = np.arange(1, 26).reshape(5, 5)
inner_3x3_matrix = martrix_5x5[1:4, 1:4]
print("5x5 Matrix:")
print(martrix_5x5)
print("\nInner 3x3 matrix:")
print(inner_3x3_matrix)

5x5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Inner 3x3 matrix:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [23]:
16.
import numpy as np
int_array=np.arange(6)
float_array=int_array.astype(float)
print("Integer Array:",int_array)
print("Float Array:",float_array)

Integer Array: [0 1 2 3 4 5]
Float Array: [0. 1. 2. 3. 4. 5.]


In [24]:
17.
import numpy as np
boole_array = np.array([[[True, False, True],
                         [False, True,False],
                         [True,True,False],
                         ]])
print(boole_array)

[[[ True False  True]
  [False  True False]
  [ True  True False]]]


In [25]:
18.
import numpy as np
complex_array = np.array([1 + 2j, 3 + 4j, 5 + 6j])
print(complex_array)

[1.+2.j 3.+4.j 5.+6.j]


In [26]:
19.
import numpy as np
string_array=np.array(["1","2","3"])
integer_array=string_array.astype(int)
print(integer_array)

[1 2 3]


In [29]:
20.
import numpy as np
float_array=np.array([1.1,2.2,3.3])
integer_array=float_array.astype(int)
print(integer_array)

[1 2 3]
